---
- name: "Establishing Variable"
  shell: "awk '{print $1}' /tmp/program_var"
  register: program_var
  tags:
    - nocron

- cron:
    name: Build a Cron Job - {{program_var.stdout}}
    state: absent
  ignore_errors: yes
  tags:
    - nocron
    
- cron:
    name: Build a Cron Job - {{program_var.stdout}}
    special_time: 'hourly'
    job: "bash /opt/plexguide/scripts/autodelete/{{program_var.stdout}}.sh"
    state: present