---
version: '2.2'
services:
 rutorrent:
   image:  linuxserver/rutorrent
   container_name: rutorrent
   ports:
     - "8999:80"
     - "51413:51413"
     - "6881:6881/udp"
     - "5000:5000"
   volumes:
     - /opt/appdata/rutorrent/:/config
     - /mnt/rutorrents/downloads:/downloads
     - /:/yourcomputer
     - /etc/localtime:/etc/localtime:ro
     - /mnt/unionfs/:/unionfs
   cpu_shares: 256
   environment:
     - PUID=1000
     - PGID=1000
   restart: unless-stopped
