---
version: '2.2'
services:
 support:
   image: admin9705/support
   container_name: support
   ports:
     - "45560:45560"
   environment:
     - PUID=1000
     - PGID=1000
     - cpu-shares=1
   tty: true
   cpu_shares: 2
   restart:
     always
