#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- name: Remove x2go Container
  docker_container:
    name: x2go
    state: absent

- name: Deploy x2go Container
  docker_container:
    name: x2go
    image: quay.io/tatsuya6502/x2go:latest
    pull: yes
    cpu_shares: 512
    published_ports:
      - "2222:22"
    user: 0
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt:/mnt"
      - "/opt:/opt"
      - "/tmp:/tmp"
      - "/mnt:/headless/Desktop/mnt:rw"
    networks:
      - name: plexguide
        aliases:
          - x2go
    restart_policy: always
    state: started

- name: Download x2go Software
  pause:
    prompt: "Visit https://wiki.x2go.org/doku.php/download:start then download the client and read the Wiki [Press Enter]"
