#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- name: Removing Prior Traefik.toml
  file:
    state: absent
    path: /opt/appdata/traefik/traefik.toml

- name: Create Basic Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/appdata/traefik
  tags:
    - main

#################################### REGISTER VAR START

- name: Register Domain
  shell: "cat /var/plexguide/server.domain"
  register: domain
  ignore_errors: True

- name: Register E-Mail
  shell: "cat /var/plexguide/server.email"
  register: email
  ignore_errors: True

#################################### REGISTER VAR END

- name: Installing Traefik.Toml
  template:
    src: traefik.toml
    dest: /opt/appdata/traefik/traefik.toml
    force: yes
    owner: 1000
    group: 1000

#################################### REPLACE START
- name: Replace Domain
  replace:
    path: /opt/appdata/traefik/traefik.toml
    regexp: yourdomain.com
    replace: "{{domain.stdout}}"

- name: Replace E-Mail
  replace:
    path: /opt/appdata/traefik/traefik.toml
    regexp: myprovider
    replace: "{{email.stdout}}"
############################# REPLACE END

- name: Remove Traefik
  docker_container:
    name: traefik
    state: absent

- name: Deploy Traefik
  docker_container:
    name: traefik
    image: traefik:latest
    pull: yes
    cpu_shares: 256
    published_ports:
      #- "8080:8080"
      - "443:443"
      - "80:80"
    env:
      PUID: 1000
      PGID: 1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - /opt/appdata/traefik/acme:/etc/traefik/acme:rw
    restart_policy: always
    state: started
    networks:
      - name: plexguide
        aliases:
          - traefik