---
########################################## RCLONE ##################

## Unencrypted
  - name: Check RClone Unencrypted
    stat:
      path: "/etc/systemd/system/rclone.service"
    register: rclone

  - name: Stop RClone Unencrypted
    systemd: state=stopped name=rclone
    when: rclone.stat.exists
    
  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/rclone.service 
    when: rclone.stat.exists

## Encrypted - Part 1
  - name: Check RClone Encrypted Part 1
    stat:
      path: "/etc/systemd/system/rclone-en.service"
    register: rclone_en

  - name: Stop RClone Encrypted Part 1
    systemd: state=stopped name=rclone-en
    when: rclone_en.stat.exists
    
  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/rclone-en.service 
    when: rclone_en.stat.exists

## Encrypted - Part 2
  - name: Check RClone Encrypted Part 2
    stat:
      path: "/etc/systemd/system/rclone-encrypt.service"
    register: rclone_encrypt

  - name: Stop RClone Encrypted Part 2
    systemd: state=stopped name=rclone-encrypt
    when: rclone_encrypt.stat.exists
    
  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/rclone-encrypt.service 
    when: rclone_encrypt.stat.exists

  ########################################## MOVE ##################

## Unencrypted
  - name: Check Move Unencrypted
    stat:
      path: "/etc/systemd/system/move.service"
    register: move

  - name: Stop Move Unencrypted
    systemd: state=stopped name=move
    when: move.stat.exists
    
  - name: Remove Move Service
    file:
      state: absent
      path: /etc/systemd/system/move.service 
    when: move.stat.exists

## Encrypted
  - name: Check Move Encrypted
    stat:
      path: "/etc/systemd/system/move-en.service"
    register: move_en

  - name: Stop Move Encrypted
    systemd: state=stopped name=move-en
    when: move_en.stat.exists
    
  - name: Remove Move Service
    file:
      state: absent
      path: /etc/systemd/system/move-en.service 
    when: move_en.stat.exists

########################################## UNIONFS ##################

## Unencrypted
  - name: Check UnionFS Unencrypted
    stat:
      path: "/etc/systemd/system/unionfs.service"
    register: unionfs

  - name: Stop UnionFS Unencrypted
    systemd: state=stopped name=unionfs
    when: unionfs.stat.exists
    
  - name: Remove UnionFS Service
    file:
      state: absent
      path: /etc/systemd/system/unionfs.service 
    when: unionfs.stat.exists

## Encrypted
  - name: Check UnionFS Encrypted
    stat:
      path: "/etc/systemd/system/unionfs-encrypt.service"
    register: unionfs_en

  - name: Stop UnionFS Encrypted
    systemd: state=stopped name=unionfs-encrypt
    when: unionfs_en.stat.exists
    
  - name: Remove UnionFS Service
    file:
      state: absent
      path: /etc/systemd/system/unionfs-encrypt.service 
    when: unionfs_en.stat.exists

########################################## DOCKERFIX ##################

  - name: Check DockerFix
    stat:
      path: "/etc/systemd/system/dockerfix.service"
    register: dockerfix

  - name: Stop DockerFix
    systemd: state=stopped name=dockerfix
    when: dockerfix.stat.exists
    
  - name: Remove DockerFix Service
    file:
      state: absent
      path: /etc/systemd/system/dockerfix.service 
    when: dockerfix.stat.exists

########################################## PLEXDRIVE4 ##################

  - name: Check PlexDrive4 Unencrypted
    stat:
      path: "/etc/systemd/system/plexdrive4.service"
    register: plexdrive4

  - name: Stop PlexDrive Unencrypted
    systemd: state=stopped name=plexdrive4
    when: plexdrive4.stat.exists
    
  - name: Remove PlexDrive4 Service
    file:
      state: absent
      path: /etc/systemd/system/plexdrive4.service 
    when: plexdrive4.stat.exists

