---
########## Create prerequisite config directories
- name: Create Basic Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/appdata/plexguide

########## Remove old existing config file
- name: Removing File Directories
  file:
    state: absent
    path:
      - /opt/appdata/plexguide/var-vpn.yml

- name: create plexguide network
  docker_network:
    name: "plexguide"
    state: present

########## Copy Var-VPN config files
- name: Installing config prerequisites
  template:
    src: var-vpn.yml
    dest: /opt/appdata/plexguide/var-vpn.yml
    force: yes

############ Ask for PIA VPN user info
- name: vpnuser
  pause:
    prompt: "What is your PIA username (If none, press ENTER to SKIP)? "
  register: pia_user

- name: vpnpassword
  pause:
   prompt: "What is your PIA password (If none, press ENTER to SKIP)? "
  register: pia_password

########## Info-Debug

- debug: msg="Using following PIA username {{pia_user.user_input}}"
- debug: msg="Using following PIA password {{pia_password.user_input}}"

############ Replace PIA VPN user info
- name: Replace pia_user with user input
  replace:
    path: /opt/appdata/plexguide/var-vpn.yml
    regexp: pia_user
    replace: "{{pia_user.user_input}}"

- name: Replace pia_password with user input
  replace:
    path: /opt/appdata/plexguide/var-vpn.yml
    regexp: pia_password
    replace: "{{pia_password.user_input}}"

#### Get IPv4 info
- name: ipv4
  shell: "hostname -I | awk '{print $1}'"
  register: ip_address

- name: Replace ipv4 with stand output
  replace:
    path: /opt/appdata/plexguide/var-vpn.yml
    regexp: ip_address
    replace: "{{ip_address.stdout}}"

- debug: msg="Your IPv4 Address is {{ip_address.stdout}}"

#### Find CIDR via subnet
- name: subnet
  shell: sudo bash /opt/plexguide/scripts/test/subnet
