#!/bin/bash
#
# [Cloudbox Ansible Role]
#
# Author:   l3uddz & Desimaniac
# URL:      https://cloudbox.rocks
#
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
# Further Enhancements & Options By: PlexGuide.com
# GitHub: https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
#################################################################################
---
- name: Create plex_dupefinder directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=true"
  with_items:
    - /opt/dupefinder

- name: Clone plex_dupefinder
  git:
    repo: https://github.com/l3uddz/plex_dupefinder/
    dest: /opt/dupefinder
    version: master
    force: yes

- name: Install pip requirements
  pip:
    requirements: /opt/dupefinder/requirements.txt
    executable: pip3

- name: Check config exists
  stat:
    path: "/opt/dupefinder/config.json"
  register: plex_dupefinder_config

- name: Import default config
  template:
    src: config.json.js2
    dest: /opt/dupefinder/config.json
    force: yes
  when: plex_dupefinder_config.stat.exists == False

- name: Set plexdupes.py as executable
  file:
    path: /opt/dupefinder/plexdupes.py
    mode: a+x

- name: Set directory permissions
  file: "path=/opt/dupefinder state=directory owner={{user}} group={{user}} recurse=yes"

- name: "Create /usr/local/bin symlink"
  file:
    src: "/opt/dupefinder/plexdupes.py"
    dest: "/usr/local/bin/plexdupes"
    state: link
